# Generated by Django 3.0.5 on 2020-08-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='needBlood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('person_mobileNumber', models.IntegerField(default=0)),
                ('person_reason', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('person_gender', models.CharField(max_length=20)),
                ('person_bloodGroup', models.CharField(max_length=20)),
                ('person_address', models.CharField(max_length=200)),
            ],
        ),
    ]
