# Generated by Django 3.0.5 on 2020-08-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='needblood',
            old_name='category',
            new_name='person_email',
        ),
        migrations.RemoveField(
            model_name='needblood',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='needblood',
            name='person_age',
            field=models.IntegerField(default=0),
        ),
    ]
